# a matrix list of variables used in the container build process
# Python version are taken from ansible's support matrix
# https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix
# version: 2025.06.01.0
include:
  # 2.17.12
  - ANSIBLE_CORE_VERSION: "2.18.6"
    PYTHON_VERSION: "3.12"
    BASE_IMAGE_NAME: ghcr.io/alexchay/python-base
    BASE_IMAGE_TAG: "3.12-slim"
    BUILD_IMAGE_NAME: "ansible-core"
    BUILD_IMAGE_TAGS: "2.18,2.18-p3.12,2.18.6,2.18.6-p3.12"
  - ANSIBLE_CORE_VERSION: "2.18.6"
    PYTHON_VERSION: "3.11"
    BASE_IMAGE_NAME: ghcr.io/alexchay/python-base
    BASE_IMAGE_TAG: "3.11-slim"
    BUILD_IMAGE_NAME: "ansible-core"
    BUILD_IMAGE_TAGS: "2.18-p3.11,2.18.6-p3.11"
  # 2.17.12
  - ANSIBLE_CORE_VERSION: "2.17.12"
    PYTHON_VERSION: "3.12"
    BASE_IMAGE_NAME: ghcr.io/alexchay/python-base
    BASE_IMAGE_TAG: "3.12-slim"
    BUILD_IMAGE_NAME: "ansible-core"
    BUILD_IMAGE_TAGS: "2.17,2.17-p3.12,2.17.12,2.17.12-p3.12"
  - ANSIBLE_CORE_VERSION: "2.17.12"
    PYTHON_VERSION: "3.11"
    BASE_IMAGE_NAME: ghcr.io/alexchay/python-base
    BASE_IMAGE_TAG: "3.11-slim"
    BUILD_IMAGE_NAME: "ansible-core"
    BUILD_IMAGE_TAGS: "2.17-p3.11,2.17.12-p3.11"
  # 2.16.14
  - ANSIBLE_CORE_VERSION: "2.16.14"
    PYTHON_VERSION: "3.12"
    BASE_IMAGE_NAME: ghcr.io/alexchay/python-base
    BASE_IMAGE_TAG: "3.12-slim"
    BUILD_IMAGE_NAME: "ansible-core"
    BUILD_IMAGE_TAGS: "2.16,2.16-p3.12,2.16.14,2.16.14-p3.12"
  - ANSIBLE_CORE_VERSION: "2.16.14"
    PYTHON_VERSION: "3.11"
    BASE_IMAGE_NAME: ghcr.io/alexchay/python-base
    BASE_IMAGE_TAG: "3.11-slim"
    BUILD_IMAGE_NAME: "ansible-core"
    BUILD_IMAGE_TAGS: "2.16-p3.11,2.16.14-p3.11"
  - ANSIBLE_CORE_VERSION: "2.16.14"
    PYTHON_VERSION: "3.10"
    BASE_IMAGE_NAME: ghcr.io/alexchay/python-base
    BASE_IMAGE_TAG: "3.10-slim"
    BUILD_IMAGE_NAME: "ansible-core"
    BUILD_IMAGE_TAGS: "2.16-p3.10,2.16.14-p3.10"